# Generated by Django 3.2 on 2022-08-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nota', models.TextField()),
                ('hora_fecha', models.DateTimeField()),
                ('finalizado', models.BooleanField()),
                ('valoracion', models.CharField(choices=[('n', 'noimportante'), ('i', 'importante'), ('u', 'urgente')], max_length=1)),
            ],
        ),
    ]
