# Generated by Django 3.2 on 2022-08-25 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0002_auto_20220825_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='finalizado',
            new_name='finalizado_e',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='hora_fecha',
            new_name='hora_fecha_e',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='nombre',
            new_name='nombre_e',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='nota',
            new_name='nota_e',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='valoracion',
            new_name='valoracion_e',
        ),
    ]
